services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: .
    volumes:
      - .:/app  # Optional: for local file syncing
    depends_on:
      - db
    entrypoint: [ "./wait-for-it.sh", "db:3306", 
      "--"]  # Optional: override CMD in Dockerfile
    command: python main.py
    ports:
      - "8080:5000"
    env_file:
      - .env
    environment:
      DB_HOST: db
volumes:
  db_data:
