services:
  app:
    build: .
    volumes:
      - .:/app  # Optional: for local file syncing
    command: python main.py  # Optional: override CMD in Dockerfile
    ports:
      - "8080:5000"
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
