CREATE TABLE IF NOT EXISTS Pokemon (
  id INTEGER PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  attack INTEGER NOT NULL,
  defense INTEGER NOT NULL,
  hp INTEGER NOT NULL,
  special_attack INTEGER NOT NULL,
  special_defense INTEGER NOT NULL,
  speed INTEGER NOT NULL,
  type1 VARCHAR(50) NOT NULL,
  type2 VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS Abilities (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL
);
